/* Dữ liệu mẫu cho hoadonnhap — chỉ dùng ở chế độ dựng thử. */
ums.demo.add({
    'TC_HoaDonNhap/LayDanhSach': {
        rows: [
            { ID: 'HN1', QLSV_NGUOIHOC_HODEM: 'Nguyễn Văn', QLSV_NGUOIHOC_TEN: 'An', SOTIEN: 9513600, NGUOITA_TENDAYDU: 'Hoàng Thu Trang',
              NGAYTAO_DD_MM_YYYY: '16/09/2026', PHANLOAI: 'CHUATHU', MOTA: 'HDDT_VNPT', DUONGDANFILEHOADON: 'HDDTFILE/nhap-HN1.pdf' },
            { ID: 'HN2', QLSV_NGUOIHOC_HODEM: 'Công ty TNHH', QLSV_NGUOIHOC_TEN: 'Hoà Bình', SOTIEN: 12000000, NGUOITA_TENDAYDU: 'Đỗ Văn Nam',
              NGAYTAO_DD_MM_YYYY: '17/09/2026', PHANLOAI: 'CHUATHU', MOTA: 'HDDT_VNPT$DOITUONGKHAC', DUONGDANFILEHOADON: 'HDDTFILE/nhap-HN2.pdf' },
            { ID: 'HN3', QLSV_NGUOIHOC_HODEM: 'Trần Thị', QLSV_NGUOIHOC_TEN: 'Bình', SOTIEN: 1263600, NGUOITA_TENDAYDU: 'Hoàng Thu Trang',
              NGAYTAO_DD_MM_YYYY: '18/09/2026', PHANLOAI: 'DATHU', MOTA: 'HDDT_VNPT', DUONGDANFILEHOADON: 'HDDTFILE/nhap-HN3.pdf' }
        ],
        pager: 3
    },
    'TC_HoaDonNhap_ChuaThu/LayDanhSach': [
        { TAICHINH_CACKHOANTHU_ID: 'A1B2C3D4E5F60718293A4B5C6D7E8F90', SOTIEN: 8250000, DONGIA: 8250000, SOLUONG: 1, DONVITINH_ID: 'DV1', DONVITINH_TEN: 'Học kỳ',
          LOAITIENTE_ID: 'LT1', LOAITIENTE_MA: 'VND', NOIDUNG: 'Học phí HK1 2025-2026', QLSV_NGUOIHOC_ID: 'QL01', DAOTAO_THOIGIANDAOTAO_ID: 'TG1',
          HINHTHUCTHU_ID: 'HT2', HINHTHUCTHU_MA: 'CK', HINHTHUCTHU_TEN: 'Chuyển khoản', NHAP_HOTENNGUOIMUAHANG: 'Nguyễn Văn An' },
        { TAICHINH_CACKHOANTHU_ID: 'B2C3D4E5F60718293A4B5C6D7E8F90A1', SOTIEN: 1263600, DONGIA: 105300, SOLUONG: 12, DONVITINH_ID: 'DV4', DONVITINH_TEN: 'Tháng',
          LOAITIENTE_ID: 'LT1', LOAITIENTE_MA: 'VND', NOIDUNG: 'BHYT 12 tháng', QLSV_NGUOIHOC_ID: 'QL01', DAOTAO_THOIGIANDAOTAO_ID: 'TG1',
          HINHTHUCTHU_ID: 'HT2', HINHTHUCTHU_MA: 'CK', HINHTHUCTHU_TEN: 'Chuyển khoản', NHAP_HOTENNGUOIMUAHANG: 'Nguyễn Văn An' }
    ],
    'TC_DaNop/ThemMoi': { rows: null, message: 'DN901,DN902' }
});
