/* Dữ liệu mẫu cho phucap — chỉ dùng ở chế độ dựng thử. */
(function () {
    var ds = [
        { ID: 'PCN1', LOAIPHUCAP_ID: 'LPC1', PHUCAP: '0.3', NHANSU_THONGTINQUYETDINH_ID: 'QDPC1', NHANSU_TTQUYETDINH_SOQD: '112/QĐ-ĐHKT', NHANSU_TTQUYETDINH_NGAYQD: '15/08/2024',
          NHANSU_TTQUYETDINH_NGAYAD: '01/09/2024', NHANSU_TTQUYETDINH_NGAYHL: '01/09/2024', NHANSU_TTQUYETDINH_NGAYHHL: '31/08/2029', HIEULUC: 1, LOAIQUYETDINH_ID: 'QD1', DONVITINH_ID: 'DVT1' },
        { ID: 'PCN2', LOAIPHUCAP_ID: 'LPC2', PHUCAP: '25', NHANSU_THONGTINQUYETDINH_ID: 'QDPC2', NHANSU_TTQUYETDINH_SOQD: '87/QĐ-ĐHKT', NHANSU_TTQUYETDINH_NGAYQD: '20/12/2023',
          NHANSU_TTQUYETDINH_NGAYAD: '01/01/2024', NHANSU_TTQUYETDINH_NGAYHL: '01/01/2024', NHANSU_TTQUYETDINH_NGAYHHL: '', HIEULUC: 1, LOAIQUYETDINH_ID: 'QD1', DONVITINH_ID: 'DVT2' }
    ];
    ums.demo.add({
        'L_QT_ThongTinPhuCap/LayDanhSach': function (o) { return o.strNhanSu_HoSoCanBo_Id === 'NS3' ? [] : ds; }
    });
})();
