/* Dữ liệu mẫu cho module dubao (Nhân sự) — chỉ dùng ở chế độ dựng thử.
   NS_DuBao/NangLuongVuotKhung dùng chung cho màn trước thời hạn (gốc gọi cùng action) nên
   dòng mẫu mang cột của CẢ HAI màn. Cơ cấu tổ chức lấy bản chung trong demo-data.js. */
ums.demo.add({
    'NS_DuBao/NangLuongThuongXuyen': [
        { HOTEN: 'Nguyễn Văn Hùng', GIOITINH_TEN: 'Nam', TRINHDOCHUYENMONCAONHAT_TEN: 'Tiến sĩ', NGACHLUONG_MA: 'V.07.01.02', BACLUONG_TEN: '3',
            HESOLUONG: '5,08', NGAYQUYETDINH: '01/10/2023', BACLUONG_TIEPTHEO_TEN: '4', HESOLUONG_TIEPTHEO: '5,42', NGAYHUONGLUONG_TIEPTHEO: '01/10/2026', SOTHANGDUOCHUONGTINHHETNAM: '3' },
        { HOTEN: 'Trần Thị Mai', GIOITINH_TEN: 'Nữ', TRINHDOCHUYENMONCAONHAT_TEN: 'Thạc sĩ', NGACHLUONG_MA: 'V.07.01.03', BACLUONG_TEN: '4',
            HESOLUONG: '3,33', NGAYQUYETDINH: '01/12/2023', BACLUONG_TIEPTHEO_TEN: '5', HESOLUONG_TIEPTHEO: '3,66', NGAYHUONGLUONG_TIEPTHEO: '01/12/2026', SOTHANGDUOCHUONGTINHHETNAM: '1' }
    ],
    'NS_DuBao/NangLuongVuotKhung': [
        { HOTEN: 'Lê Quang Minh', DAOTAO_COCAUTOCHUC: 'Khoa Kinh tế', GIOITINH_TEN: 'Nam', LOAIHOCVI: 'Tiến sĩ', TRINHDOCHUYENMONCAONHAT_TEN: 'Tiến sĩ',
            NGACHLUONG_MA: 'V.07.01.03', BACLUONG_TEN: '8', HESOLUONG: '4,65', NGAYQUYETDINH: '01/03/2024', BACLUONG_TIEPTHEO_TEN: '9', HESOLUONG_TIEPTHEO: '4,98',
            SOTHANGNANGLUONGTRUOCHAN: '9', NGAYHUONGLUONG_TIEPTHEO: '01/06/2026', THANHTICHDUOCGHINHANTRUOCHAN: 'Chiến sĩ thi đua cơ sở 2025',
            BACLUONGCUOICUANGACH: '9', HESOLUONGBACCUOICUANGACH: '4,98', LAYNGAYHUONGLUONGVUOTKHUNG: '01/03/2023', PHANTRAMVUOTKHUNGDAHUONG: '5',
            NGAYHUONGVUOTKHUNGTIEP_HIENTAI: '01/03/2026', PHANTRAMVUOTKHUNGTIEP: '6', NGAYHUONGVUOTKHUNGTIEP: '01/03/2027', SOTHANGDUOCHUONGTINHTU: '10' }
    ]
});
